import { NextPage } from 'next'
import Head from 'next/head'

export const getStaticProps = async () => {
  const res = await fetch('https://restcountries.com/v3.1/all');
  const data = await res.json();
  console.log(data[0]);

  return {
    props: {allCountriesData: data,}
  }
}

const Home: NextPage = ({allCountriesData}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='text-red-500'>Hello</main>
    </>
  )
}

export default Home
